# Generated by Django 5.0.2 on 2024-02-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_cleaneravailability_delete_cleanerservicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaneravailability',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
