# Generated by Django 5.0.2 on 2024-02-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_cleaneravailability_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cleaneravailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='cleaneravailability',
            name='start_time',
        ),
        migrations.AddField(
            model_name='cleaneravailability',
            name='timeslot',
            field=models.ManyToManyField(related_name='available_slots', to='bookings.timeslot'),
        ),
    ]
